name:                distributed-process-gossip
version:             0.1.0.0
github:              "kaffepanna/distributed-process-gossip"
license:             BSD3
author:              "Patrik"
maintainer:          "pettersson.pa@gmail.com"
copyright:           "2018 Patrik"

extra-source-files:
- README.md
- ChangeLog.md

# Metadata used when publishing your package
# synopsis:            Short description of your package
# category:            Web

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description:         Please see the README on Github at <https://github.com/kaffepanna/distributed-process-gossip#readme>

dependencies:
- base >= 4.7 && < 5

library:
  source-dirs: src

executables:
  distributed-process-gossip-exe:
    main:                Main.hs
    source-dirs:         app
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - distributed-process-gossip

tests:
  distributed-process-gossip-test:
    main:                Spec.hs
    source-dirs:         test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - distributed-process-gossip
